import "./globals.css";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import StyledComponentsRegistry from "./lib/registry";
import { getClient, query } from "./lib/client";
import { GET_THEME } from "../utils/getHostThemes/gql";
import { BaseProvider } from "../context/BaseProvider";
import { theme } from "@/design-system";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const materialSymbols = localFont({
  variable: "--font-family-symbols", // Variable name (to reference after in CSS/styles)
  style: "normal",
  src: "../../node_modules/material-symbols/material-symbols-rounded.woff2", // This is a reference to woff2 file from NPM package "material-symbols"
  display: "block",
  weight: "100 700",
});

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const { data } = await getClient().query({
  //   query: GET_THEME,
  //   variables: {
  //     host: "localhost:3000",
  //   },
  // });

  const { data, ...rest } = await query({
    query: GET_THEME,
    variables: {
      host: "localhost:3000",
    },
  });

  return (
    <html lang="en" className={`${materialSymbols.variable}`}>
      <head>
        {/* <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200&display=optional"
        /> */}
      </head>
      <body className={inter.className}>
        <BaseProvider theme={theme ?? {}}>
          <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        </BaseProvider>
      </body>
    </html>
  );
}
