import "./globals.css";
import { Inter } from "next/font/google";
import StyledComponentsRegistry from "./lib/registry";
import { getClient } from "./lib/client";
import { GET_THEME } from "../utils/getHostThemes/gql";
import { BaseProvider } from "../context/BaseProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { data } = await getClient().query({
    query: GET_THEME,
    variables: {
      host: "localhost:3000",
    },
  });
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200&display=optional"
        />
      </head>
      <body className={inter.className}>
        <BaseProvider theme={data.results}>
          <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        </BaseProvider>
      </body>
    </html>
  );
}
